RD=rd/s/q
RM=del/q
DD=D:\tools\dd.exe
NASM=D:\nasm\latest\nasm.exe
PS=powershell -executionpolicy remotesigned

OUTDIR=..\bin
OBJDIR=obj
VMNAME=Raw
VHDX=S:\Hyper-V\Raw\boot.vhdx
DEVICE=\??\PhysicalDrive4
